apiVersion: v1
kind: Service
metadata:
  name: scaletestapp-service
  labels:
    app: scaletestapp
spec:
  selector:
    app: scaletestapp
  ports:
    - name: metrics
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
